studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView, TemplateView

from .settings import MEDIA_ROOT, DEBUG

from students.views.students import StudentUpdateView, StudentDeleteView
from students.views.groups import GroupDeleteView, groups_add,groups_edit, groups_list
from students.views.journal import JournalView


js_info_dict = {
    'packages':('students',),
}

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),
    # Students urls
    url(r'^$', 'students.views.students.students_list', name='home'),
    url(r'^students/add/$', 'students.views.students.students_add', name='students_add'),
    url(r'^students/(?P<pk>\d+)/edit/$', StudentUpdateView.as_view(), name='students_edit'),
    url(r'^students/(?P<pk>\d+)/delete/$', StudentDeleteView.as_view(), name='students_delete'),

    # Groups urls
    url(r'^groups/$', login_required(groups_list), name='groups'),
    url(r'^groups/add/$', login_required(groups_add), name='groups_add'),
    url(r'^groups/(?P<gid>\d+)/edit/$', 'students.views.groups.groups_edit', name='groups_edit'),
    url(r'^groups/(?P<pk>\d+)/delete/$', GroupDeleteView.as_view(), name='groups_delete'),

    # Journal urls
    url(r'^journal/$', JournalView.as_view(), name='journal'),
    url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),
    url(r'^admin/', include(admin.site.urls)),

    # Exam urls
    url(r'^exams/$', 'students.views.exams.exam_list', name='exams'),
    url(r'^exams/add/$', 'students.views.exams.exam_add', name='exam_add'),
    url(r'^exams/(?P<eid>\d+)/edit/$', 'students.views.exams.exam_edit', name='exam_edit'),
    url(r'^exams/(?P<eid>\d+)/delete/$','students.views.exams.exam_delete', name='exam_delete'),
    url(r'^exams/(?P<eid>\d+)/result/$', 'students.views.exams.exam_result', name='exam_result'),

    #Contact Admin Form
    url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin', name='contact_admin'),

    #User Related urls
    url(r'^users/profile/$', login_required(TemplateView.as_view(template_name='registration/profile.html')), name='profile'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
        name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls',
        namespace='users')),

    #Social Auth Related urls
    url('^social/', include('social.apps.django_app.urls', namespace='social')),

)
if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/models/exams.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Exam(models.Model):
    """Exam Model"""
    class Meta(object):
        verbose_name = _(u"Exam")
        verbose_name_plural = _(u"Exams")
        ordering = ['date']

    subject = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u'Subject'))

    date = models.DateTimeField(
        blank=False,
        verbose_name=_(u'Date'))

    teacher=models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u'Teacher'))

    group = models.OneToOneField('Group',
        verbose_name=_(u"Group"),
        blank=False)

    def __unicode__(self):
        return u"%s %s %s %s" % (self.subject, self.teacher, self.date, self.group)

students/models/groups.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Group(models.Model):
    """Group Model"""
    class Meta(object):
        verbose_name = _(u"Group")
        verbose_name_plural = _(u"Groups")
        ordering = ['title']

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Title"))

    leader = models.OneToOneField('Student',
        verbose_name=_(u"Leader"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL)

    notes = models.TextField(
        blank=True,
        verbose_name=_(u"Additional Notes"))

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
        else:
            return u"%s" % (self.title,)

students/models/students.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Student(models.Model):
    """Student Model"""
    class Meta(object):
        verbose_name = _(u"Student")
        verbose_name_plural = _(u"Students")
        ordering = ['last_name']

    first_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"First Name"))

    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Last Name"))

    middle_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=_(u"Second Name"),
        default='')

    birthday = models.DateField(
        blank=False,
        verbose_name=_(u"Date of birth"),
        null=True)

    photo = models.ImageField(
        blank=True,
        verbose_name=_(u"Photo"),
        null=True)

    student_group = models.ForeignKey('Group',
        verbose_name=_(u"Group"),
        blank=False,
        null=True,
        on_delete=models.PROTECT)

    ticket = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Ticket"))

    notes = models.TextField(
        blank=True,
        verbose_name=_(u"Additional Notes"))

    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)

students/views/contact_admin.py
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import permission_required
from django.utils.translation import ugettext_lazy as _
import logging

from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        #call original initializator
        super(ContactForm, self).__init__(*args, **kwargs)

        #this helper object allows us to customize form
        self.helper =FormHelper()

        #form tag attributes
        self.helper.form_class = 'form_horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('contact_admin')

        #twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        #form buttons
        self.helper.add_input(Submit('send_button', _(u'Send')))


    from_email = forms.EmailField(
    label=_(u"Your Email Address"))

    subject = forms.CharField(
    label=_(u"Email Subject"),
    max_length=128)

    message = forms.CharField(
    label=_(u"Email Body"),
    max_length=2560,
    widget=forms.Textarea)


@permission_required('auth.add_user')
def contact_admin(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, message, from_email, [ADMIN_EMAIL])
            except Exception:
                message = _(u"An error occured during email transfer. Please, "
                    "try again later.")
                logger = logging.getLogger(__name__)
                logger.exception(message)
            else:
                message = _(u"Message sent successfully!")
            return HttpResponseRedirect(u'%s?status_message=%s' % (reverse('contact_admin'), message))

    else:
        form = ContactForm()
    return render(request, 'contact_admin/form.html', {'form':form})

students/views/exams.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from ..models import Exam
from ..util import paginate, get_current_group

def exam_list(request):
    current_group = get_current_group(request)
    if current_group:
        exams = Exam.objects.filter(group=current_group)
    else:
        exams = Exam.objects.all()
    order_by = request.GET.get('order_by', '')
    if order_by in ('subject', 'date', 'teacher', 'group'):
        students = exams.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            exams = exams.reverse()
    return render(request, 'students/exam_list.html',{'exams':exams})

def exam_add(request):
    return HttpResponse('<h1>Exam Add Form</h1>')

def exam_edit(request, eid):
    return HttpResponse('<h1>Edit Exam %s</h1>' % eid)

def exam_delete(request, eid):
    return  HttpResponse('<h1>Delete Exam %s</h1>' % eid)

def exam_result(request, eid):
    return  HttpResponse('<h1>Result Exam %s</h1>' % eid)

students/views/groups.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import UpdateView, DeleteView
from django.utils.translation import ugettext as _

from ..models import Group, Student
from ..util import paginate


class GroupDeleteView(DeleteView):
    model = Group
    template_name = 'students/groups_confirm_delete.html'

    def get_success_url(self):
        return u'%s?status_message=%s' % (reverse('groups'),
        _(u"Group deleted successfully!"))


def groups_list(request):
    groups = Group.objects.all()
    order_by = request.GET.get('order_by', '')
    if order_by in ('title',):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            groups = groups.reverse()

    # paginate groups
    context = paginate(groups, 2, request, {}, var_name='groups')

    return render(request, 'students/groups_list.html', context)

def groups_add(request):
    if request.method == 'POST':
        if request.POST.get('add_button') is not None:
            errors = {}
            data = {}


            title = request.POST.get('title','').strip()
            if not title:
                errors['title'] = _(u'Group field is required')
            else:
                groups_count = Group.objects.filter(title=title)
                if len(groups_count) != 0:
                    errors['title'] = _(u'A group of that name already exists')
                data['title'] = title

            leader = request.POST.get('leader','').strip()
            if not leader:
                pass
            else:
                students = Student.objects.filter(pk=leader)
                leaders = Group.objects.filter(leader=leader)
                if len(students) != 1:
                    errors['leader'] = _(u'Select correct student')
                elif len(leaders) != 0:
                    errors['leader'] = _(u'This student is the leader of another group')
                else:
                    data['leader'] = students[0]

            if not errors:
                group = Group(**data)
                group.save()

                return HttpResponseRedirect(
                    u'%s?status_message=%s' %
                    (reverse('groups'), _(u"Group added successfully!")))

            else:
                return render(request, 'students/groups_add.html',
                    {'students': Student.objects.all().order_by('last_name'),
                     'errors': errors})

        elif request.POST.get('cancel_button') is not None:
            # redirect to home page on cancel button
            return HttpResponseRedirect(
                u'%s?status_message=%s!' %
                (reverse('group'), _(u"Adding a group canceled!")))
    else:
        # initial form render
        return render(request, 'students/groups_add.html',
            {'students': Student.objects.all().order_by('last_name')})



    return render(request, 'students/groups_add.html',
        {'students': Student.objects.all().order_by('last_name')})

def groups_edit(request, gid):
    return HttpResponse('<h1>Edit Group %s</h1>' % gid)

def groups_delete(request, gid):
    return HttpResponse('<h1>Delete Group %s</h1>' % gid)

students/views/journal.py
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr

from django.core.urlresolvers import reverse
from django.views.generic.base import TemplateView
from django.http import JsonResponse

from ..models import MonthJournal, Student
from ..util import paginate, get_current_group


class JournalView(TemplateView):
    template_name = 'students/journal.html'



    def post(self, request, *args, **kwargs):
        data = request.POST

        # prepare student, dates and presence data
        current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
        month = date(current_date.year, current_date.month, 1)
        present = data['present'] and True or False

        student = Student.objects.get(pk=data['pk'])

        # get or create journal object for given student and month
        journal = MonthJournal.objects.get_or_create(student=student,
             date=month)[0]

        # set new presence on journal for given student and save result
        setattr(journal, 'present_day%d' % current_date.day, present)
        journal.save()

        # return success status
        return JsonResponse({'status': 'success'})


    def get_context_data(self, **kwargs):
        # get context data from TemplateView class
        context = super(JournalView, self).get_context_data(**kwargs)

        # check if we need to display some specific month
        if self.request.GET.get('month'):
            month = datetime.strptime(self.request.GET['month'], '%Y-%m-%d'
                ).date()
        else:
            # otherwise just displaying current month data
            today = datetime.today()
            month = date(today.year, today.month, 1)

        # calculate current, previous and next month details;
        # we need this for month navigation element in template
        next_month = month + relativedelta(months=1)
        prev_month = month - relativedelta(months=1)
        context['prev_month'] = prev_month.strftime('%Y-%m-%d')
        context['next_month'] = next_month.strftime('%Y-%m-%d')
        context['year'] = month.year
        context['month_verbose'] = month.strftime('%B')

        # we'll use this variable in students pagination
        context['cur_month'] = month.strftime('%Y-%m-%d')

        # prepare variable for template to generate
        # journal table header elements
        myear, mmonth = month.year, month.month
        number_of_days = monthrange(myear, mmonth)[1]
        context['month_header'] = [{'day': d,
            'verbose': day_abbr[weekday(myear, mmonth, d)][:3]}
            for d in range(1, number_of_days+1)]


        # check if we need to show only one group of students
        current_group = get_current_group(self.request)

        # get all students from database,
        if kwargs.get('pk'):
            queryset = [Student.objects.get(pk=kwargs['pk'])]
        elif current_group:
            queryset = Student.objects.filter(student_group=current_group)
        else:
            queryset = Student.objects.all().order_by('last_name')

        # url to update student presence, for form post
        update_url = reverse('journal')

        # go over all students and collect data about presence
        # during selected month
        students = []
        for student in queryset:
            # try to get journal object by month selected
            # month and current student
            try:
                journal = MonthJournal.objects.get(student=student, date=month)
            except Exception:
                journal = None

            # fill in days presence list for current student
            days = []
            for day in range(1, number_of_days+1):
                days.append({
                    'day': day,
                    'present': journal and getattr(journal, 'present_day%d' %
                        day, False) or False,
                    'date': date(myear, mmonth, day).strftime(
                        '%Y-%m-%d'),
                })

            # prepare metadata for current student
            students.append({
                'fullname': u'%s %s' % (student.last_name, student.first_name),
                'days': days,
                'id': student.id,
                'update_url': update_url,
            })

        # apply pagination, 10 students per page
        context = paginate(students, 10, self.request, context,
            var_name='students')

        # finally return updated context
        # with paginated students
        return context

students/templates/students/base.html

{% load i18n %}
{% load static from staticfiles %}


<!DOCTYPE html>
<html lang="uk">

    <head>
        <meta charset="utf-8"/>
        <title>{% trans "Student Accounting Service" %} - {% block meta_title %}{% endblock meta_title %}</title>
        <meta name="description" value="{% trans "APP to manage students database" %}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
        <link rel="stylesheet"
              href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet"
              href="{{ PORTAL_URL }}{% static "css/main.css" %}">


        {% block extra_css %}{% endblock extra_css %}


    </head>

    <body>

        <!-- Start Conteiner-->
        <div class="container">

            <!--Start Header-->
            <div class="row" id="header">

                {% block logo %}
                <!--Logo-->
                <div class="col-xs-6">
                    <h1>{% trans "Student Accounting Service" %}</h1>
                </div>
                {% endblock logo %}

                {% block groups_selector %}
                <!--Groups Selector-->
                {% if user.is_authenticated %}
                <div class="col-xs-4" id="group-selector">
                    <strong>{% trans "Group" %}:</strong>
                    <select>
                        <option value="">{% trans "All Students" %}</option>
                        {% for group in GROUPS %}
                        <option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>
                        {{ group.title }}{% if group.leader %}, {{ group.leader }}{% endif %}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- User's toolbar for authenticated users -->
                <div class="col-xs-2" id="user-toolbar">
                  <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
                  <a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
                </div>

                {% else %}

                <!-- User's toolbar for anonymous users -->
                <div class="col-xs-6" id="user-toolbar">
                  <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">{% trans "via Facebook" %}</a> |
                  <a href="{% url "users:auth_login" %}">{% trans "Login" %}</a> |
                  <a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
                </div>
                {% endif %}
                {% endblock groups_selector %}
            </div>
            <!--End Header-->



            <!--Start SubHeader-->
            <div class="row" id="sub-header">
                <div class="col-xs-12">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" {% if request.path == '/' %}
                        class="active"{% endif %}><a href="{% url 'home' %}">{% trans "Students" %}</a></li>
                        {% if user.is_authenticated %}
                        <li role="presentation"{% if '/journal' in request.path %}
                        class="active"{% endif %}><a href="{% url 'journal' %}">{% trans "Journal" %}</a></li>
                        <li role="presentation"{% if '/groups' in request.path %}
                        class="active"{% endif %}><a href="{% url 'groups' %}">{% trans "Groups" %}</a></li>
                        <li role="presentation"{% if '/exams' in request.path %}
                        class="active"{% endif %}><a href="{%url 'exams' %}">{% trans "Exams" %}</a></li>
                        {% endif %}

                        {% if perms.auth.add_user %}
                        <li role="presentation"{% if '/contact-admin' in request.path %}
                        class="active"{% endif %}><a href="{%url 'contact_admin' %}">{% trans "Contact" %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!--End SubHeader-->

            <!-- Start Content Columns -->
            <div class="row" id="content-columns">
                <div class="col-xs-12" id="content-column">

                  {% block status_message %}
                  {% if request.GET.status_message %}
                    <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
                  {% endif %}
                  {% endblock %}


                    <h2>{% block title %}{% endblock title %}</h2>
                    {% block content %}{% endblock content %}

                </div>
            </div>
            <!-- End Content Columns -->
            <div>

            </div>
            <div class="col-xs-12">
                <div class="col-xs-9"></div>
                <div class="col-xs-3">
                    <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                    {% endfor %}
                    </select>
                    <input type="submit" value="Go" />
                    </form>
                </div>
              </div>

            {% block footer %}
            <!--Start Footer-->
            <div class="row" id="footer">
                <div class="col-xs-12">
                    &copy; 2015 {% trans "Students Accounting Service" %}
                </div>
            </div>
            <!--End Footer-->
            {% endblock footer %}

        </div>
        <!--End Container-->

        <!-- Modal Boilerplate -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
              aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
              </div>
              <div class="modal-body"><!-- --></div>
              <div class="modal-footer"><!-- --></div>
            </div>
          </div>
        </div>

        <div class="modal1"><!-- Place at bottom of page --></div>

        <!--Javascripts Selection-->
        <script src="{% static "js/moment.min.js" %}"></script>
        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/jquery.form.min.js" %}"></script>
        <script src="{% static "js/jquery.cookie.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
        <script src="{% static "js/uk.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
        <script src="{% static "js/jquery.cookie.js" %}"></script>
        <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
        <script src="{% static "js/uk.js" %}"></script>
        <script src="{% url "django.views.i18n.javascript_catalog" %}"></script>
        <script src="{% static "js/main.js" %}"></script>

        {% block extra_js %}{% endblock extra_js %}

    </body>

</html>

students/templates/students/demo.html
<head>
    <meta charset="UTF-8"/>
</head>
<form action="/submit_form.html" method="post"
    enctype="multipart/form-data" name="myform">

    <input type="hidden" value="27" name="student_id" />

    <div>
        <label for="first_name">Ваше ім'я</label>
        <input type="text" value="" name="first_name"
            id="first_name" />
    </div>

    <div>
        <label for="graduated">Закінчили навчання?</label>
        <input type="checkbox" checked="1" name="graduated"
            value="1" id="graduated" />
    </div>

    <div>
        <label for="gender">Ваша стать</label>
        <input type="radio" name="gender" value="male"
            id="gender" />
        <input type="radio" name="gender" value="female" />
    </div>

    <div>
        <label for="age">Ваш вік</label>
        <select name="age" id="age">
            <option value="">
                Будь-ласка, виберіть ваш вік
            </option>
            <option value="10">Більше ніж 10</option>
            <option value="20">Більше ніж 20</option>
        </select>
    </div>

    <div>
        <label for="info">Трохи про себе</label>
        <textarea id="info"></textarea>
    </div>
    <input type="submit" name="save_button"
           value="Зберегти" />
</form>

students/templates/students/exam_list.html
{% extends "students/base.html" %}

{% load i18n %}
{% load static from staticfiles %}

{% block meta_title %}{% trans "Exams" %}{% endblock meta_title %}

{% block title %}{% trans "Exams List" %}{% endblock title %}



{% block content %}
<a href="{% url 'exam_add' %}" class="btn btn-primary">{% trans "Add Exam" %}</a>

    <!--Start Students Listing-->
    <table class="table">
        {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
            <thead>
            <a>
                <th>#</th>
                <th><a href="{% url 'exams' %}?order_by=subject{% if order_by == 'subject' and reverse != '1' %}&amp;reverse=1{% endif %}">
                    {% trans "Subject" %}
                    {% if order_by == 'subject' and reverse != '1' %}&uarr;
                    {% elif order_by == 'subject' and reverse == '1' %}&darr;
                    {% endif %}</a></th>
                <th><a href="{% url 'exams' %}?order_by=date{% if order_by == 'date' and reverse != '1' %}&amp;reverse=1
                {% elif order_by == '' and reverse != '1' %}&amp;reverse=1{% endif %}">{% trans "Date" %}
                    {% if order_by == 'date' and reverse != '1' %}&uarr;
                    {% elif order_by == '' and reverse != '1' %}&uarr;
                    {% elif order_by == 'date' and reverse == '1' %}&darr;
                    {% endif %}</a></th>
                <th><a href="{% url 'exams' %}?order_by=teacher{% if order_by == 'teacher' and reverse != '1' %}&amp;reverse=1{% endif %}">
                  {% trans "Teacher" %}
                    {% if order_by == 'teacher' and reverse != '1' %}&uarr;
                    {% elif order_by == 'teacher' and reverse == '1' %}&darr;
                    {% endif %}</a></th>
                <th><a href="{% url 'exams' %}?order_by=group{% if order_by == 'group' and reverse != '1' %}&amp;reverse=1{% endif %}">
                  {% trans "Group" %}
                    {% if order_by == 'group' and reverse != '1' %}&uarr;
                    {% elif order_by == 'group' and reverse == '1' %}&darr;
                    {% endif %}</a></th>
            </tr>
            </thead>
        {% endwith %}
        <tbody>
            {% for exam in exams %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a title="{% trans "Edit" %}" href="{% url 'exam_edit' exam.id %}" >{{ exam.subject }}</a></td>
                <td>{{ exam.date }}</td>
                <td>{{ exam.teacher }}</td>
                <td>{{ exam.group }}</td>
                <td>
                    <div class="btn-group">
                            <a href="{% url 'exam_result' exam.id %}">
                            <button type="button" class="btn btn-default btn-sm">
                              <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                            </button></a>
                            <a href="{% url 'exam_edit' exam.id %}">
                            <button type="button" class="btn btn-default btn-sm">
                              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button></a>
                            <a href="{% url 'exam_delete' exam.id %}">
                            <button type="button" class="btn btn-default btn-sm">
                              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </button></a>
                        </ul>
                    </div>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <!--End Students Listing-->

    {% include 'students/pagination.html' %}

{% endblock content %}

students/templates/students/hello_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
hello world
</body>
</html>